name: Build and test nrt

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]

    steps:
      - name: checkout repo + LFS files
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: checkout lfs objects
        run: git lfs checkout
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies and package
        run: |
          python -m pip install --upgrade pip
          pip install pytest wheel
          pip install .
      - name: Test with pytest
        run: |
          pytest
